import random
player,enemies,enemyL,stats,lvlcheck,town,ok,ok2,ok3 = {'name':raw_input('==== 25 line TXT RPG ====\n\nWelcome! What is your name: '),'HP':100,'LVL':1,'XP':0,'ATK':1,'DEF':1,'MP':5,'gold':0,'quest':False,'questsFinished':0,'questNums':{'Orc':0,'Wizard':0,'Dragon':0,'Goblin':0,'Fairy':0},'questGoal':{'name':'because you have no quest','num':'nothing'}},[{'name':'Orc','HP':15,'ATK':4,'XP':1,'chat':'He grunts at you and then charges [-HP]','chatE':'-(random.randint(3,5))'},{'name':'Wizard','HP':8,'ATK':7,'chat':'The wizard says "You are brave to face me, but I will not spare your life. However I will give you a small advantage"[+HP]','chatE':'+(random.randint(1,4))','XP':3},{'name':'Dragon','HP':25,'ATK':6,'chat':'He roars tremendously and attacks [-HP]','chatE':'-(random.randint(1,4))','XP':5},{'name':'Goblin','HP':10,'ATK':3,'chat':'the goblin says "Give me all your gold!!!" and stabs at you [-HP]','chatE':'-(random.randint(0,1))','XP':1},{'name':'Fairy','HP':5,'ATK':1,'chat':'The fairy cries out "Please don\'t hurt me adventurer! I am here to help you! Take this". Your HP suddenly increases! [+HP]','chatE':'+(random.randint(1,15))','XP':1}],{'Orc':0,'Wizard':1,'Dragon':2,'Goblin':3,'Fairy':4}, lambda:"\n---STATS---\nNAME: "+player['name']+"\nHP: "+str(player['HP'])+"\nLVL: "+str(player['LVL'])+"\nXP: "+str(player['XP'])+"/"+str(player['LVL']*10)+"\nATK: "+str(player['ATK'])+"\nDEF: "+str(player['DEF'])+"\nMP: "+str(player['MP'])+"\nGOLD: "+str(player['gold'])+"\nQUEST: You have to kill "+str(player['questGoal']['num'])+" "+player['questGoal']['name']+"s", lambda xp,lvl: xp >= lvl*10,True,raw_input('\n*Hint!* When you have enough XP, go to the guild master to level up!'),raw_input('\n*Hint!* Try talking to different people and enemies! Maybe you can benefit from it'),raw_input('\n*Hint!* The more quests you finish, the higher your reward for each quest!')
while player['HP'] > 0:
    num = random.randint(0,4)
    if not town: enemy,ok,fighting = {'name':enemies[num]['name'],'ATK':enemies[num]['ATK'],'HP':enemies[num]['HP'],'chat':enemies[num]['chat'],'chatE':enemies[num]['chatE'],'XP':enemies[num]['XP']}, raw_input(stats()+"\n-----------\n\nYou have just encountered a "+enemies[num]['name']+"!"), True
    while not town and enemy['HP'] > 0 and player['HP'] > 0 and fighting:
        action = raw_input(stats()+"\n-----------\n\n"+enemy['name']+" has "+str(enemy['HP'])+" hp remaining"+"\n\nWhat would you like to do?\n[1] Attack\n[2] Defend\n[3] Magic\n[4] Talk\n[5] Run\n[6] Run to Town\n\n>> ")
        if action == '1': player['HP'],enemy['HP'],ok = player['HP'] - (enemy['ATK']-player['DEF']), enemy['HP'] - player['ATK'], raw_input('\nYou do '+str(player['ATK'])+' damage and take '+str(enemy['ATK'])+' damage, but block '+str(player['DEF'])+' damage! [-HP]')
        elif action == '2': player['HP'],ok = player['HP'] - random.randint(0,1), raw_input('You try to block, and you only take a little damage [-HP]')
        elif action == '3' and player['MP'] > 0: player['MP'],enemy['HP'],ok = player['MP']-1, enemy['HP'] - random.randint(4,12), raw_input('You summon forth a large magical burst from deep within, causing a random amount of damage! [-MP]')
        elif action == '4' and enemy['name'] != 'Fairy': player['HP'],ok = player['HP'] + eval(enemy['chatE']), raw_input(''+enemy['chat'])
        elif action == '4' and enemy['name'] == 'Fairy': player['HP'],enemy['HP'],ok = player['HP'] + eval(enemy['chatE']), 0, raw_input(enemy['chat'])
        elif action == '5': player['HP'],fighting,ok = player['HP'] - enemy['ATK'], False, raw_input('You run away, but take some damage as you do so [-HP]')
        elif action == '6': player['HP'],fighting,town,ok = player['HP'] - enemy['ATK'],False,True,raw_input('You escape battle, taking some damage. You head off towards the local town [-HP]')
    if not town and enemy['HP'] <= 0: player['gold'],player['XP'],player['questNums'][enemy['name']],ok = player['gold']+random.randint(0,2),player['XP']+enemy['XP'],player['questNums'][enemy['name']] + 1,raw_input('The '+enemy['name']+' dies, and you gain '+str(enemy['XP'])+' xp, and pick up some gold! [+XP][+GOLD]')
    while player['HP'] > 0 and town:
        action = raw_input(stats()+"\n-----------\n\nYou are in the small town of Towneshire. What would you like to do?\n[1] Buy some food at the Inn for 2 gold\n[2] Spend a night at the Inn for 10 gold\n[3] Speak with the guild master\n[4] Speak with the group of warriors in the alley\n[5] Leave town\n\n>> ")
        if action == '1' and player['gold'] >= 2: player['HP'],player['gold'],ok = player['HP'] + 5,player['gold'] - 2,raw_input('You grab a bite at the Inn, and regain 5 HP')
        elif action == '2' and player['gold'] >= 10: player['HP'],player['gold'],ok = player['HP'] + 30,player['gold'] - 10,raw_input('You spend a restful night at the Inn, and regain 30 HP')
        elif action == '3' and lvlcheck(player['XP'],player['LVL']): player['LVL'],player['HP'],player['ATK'], player['DEF'],player['XP'],player['MP'],ok = player['LVL']+1,player['HP']+50,player['ATK']+1,player['DEF']+1,player['XP']-player['LVL']*10,player['MP']+6+player['LVL'],raw_input("You visit the guild master and he notices you have gained much experience. You level up! [+LVL][+HP][+ATK][+DEF][+MP]")
        elif action == '3' and not player['quest']: player['quest'],player['questGoal']['num'],player['questGoal']['name'],ok = True, random.randint(3,5)+player['questsFinished'],enemies[random.randint(0,4)]['name'],raw_input('\nThe guild master welcomes you and assignes you a quest! [+QUEST]')
        elif action == '3' and player['quest'] and player['questNums'][player['questGoal']['name']] >= player['questGoal']['num']: player['questsFinished'],player['gold'],player['XP'],player['quest'],player['questNums'],player['questGoal'],ok = player['questsFinished']+1,player['gold'] + random.randint(5,10)+player['questsFinished'],player['XP']+int((enemies[enemyL[player['questGoal']['name']]]['XP']*player['questGoal']['num'])/2)+player['questsFinished'],False,{'Orc':0,'Wizard':0,'Dragon':0,'Goblin':0,'Fairy':0},{'name':'because you have no quest','num':'nothing'},raw_input("You approach the guild master and inform him that you have completed your quest. He rewards you well [+XP][+GOLD]")
        elif action == '4' and player['HP'] > 6: player['HP'],player['XP'],ok = player['HP'] - 6,player['XP'] + 1,raw_input('They beat you up, but you learn from the experience [+XP][-HP]')
        elif action == '5': town,fighting = False,True
raw_input("You have adventured far, brave "+player['name']+", but alas your journey has come to an end. You have been slain by a "+enemy['name']+". Your final stats:\n"+stats()+"\n-----------\n\nYour Final Score: "+str(int(player['LVL']*20+player['XP']+player['gold']*2+player['MP']*2+player['questsFinished']*5)))